version: '3'

services:
    app:
        image: docker.pkg.github.com/chivincent/shorter-url/shorter-url
        ports:
            - 8080:80
        volumes:
            - ./database/database.sqlite:/www/database/database.sqlite
            - ./storage/logs/nginx/:/var/log/nginx/
            - ./storage/logs/laravel.log:/www/storage/logs/laravel.log
        env_file: .env
