name: Build

on: 
  push: 
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t docker.pkg.github.com/chivincent/shorter-url/app .
      - name: Publish to GitHub Package
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chivincent/shorter-url/app
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com